export const ERROR_CODES = Object.freeze({
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
  COMPOSER_NOT_FOUND: 'COMPOSER_NOT_FOUND',
  PROJECT_CREATE_FAILED: 'PROJECT_CREATE_FAILED',
  PROJECT_INSTRUCTIONS_FAILED: 'PROJECT_INSTRUCTIONS_FAILED',
  RESOURCE_DOWNLOAD_FAILED: 'RESOURCE_DOWNLOAD_FAILED',
  RESOURCE_UPLOAD_FAILED: 'RESOURCE_UPLOAD_FAILED',
  MODEL_DID_NOT_START: 'MODEL_DID_NOT_START',
  MODEL_RESPONSE_TIMEOUT: 'MODEL_RESPONSE_TIMEOUT',
  CHAT_LENGTH_LIMIT: 'CHAT_LENGTH_LIMIT',
  PATCH_DOWNLOAD_AMBIGUOUS: 'PATCH_DOWNLOAD_AMBIGUOUS',
  PATCH_DOWNLOAD_FAILED: 'PATCH_DOWNLOAD_FAILED',
  REMOTE_ARTIFACT_UPLOAD_FAILED: 'REMOTE_ARTIFACT_UPLOAD_FAILED',
  TASK_PROTOCOL_MISSING: 'TASK_PROTOCOL_MISSING',
  LOGIN_OR_CHALLENGE_REQUIRED: 'LOGIN_OR_CHALLENGE_REQUIRED',
  UI_SELECTOR_INCOMPATIBLE: 'UI_SELECTOR_INCOMPATIBLE'
});

export class RunnerError extends Error {
  constructor(code, message, details = undefined) {
    super(message);
    this.name = 'RunnerError';
    this.code = code;
    this.details = details;
  }
}
